# Generated by Django 3.1.3 on 2020-11-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0003_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='file',
            field=models.ImageField(upload_to='media'),
        ),
    ]
