# Generated by Django 3.1.3 on 2020-11-27 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0004_auto_20201124_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gimage', models.ImageField(upload_to='gallery')),
                ('progallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='ss.hotel')),
            ],
        ),
    ]
